export const PA_STEPS = {
    INSTAKIT_ALLOCATION: 'INSTAKIT_ALLOCATION',
    ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
    FUND_TRANSFER: 'FUND_TRANSFER',
    DIGITAL_ACCOUNT_OPENING: 'DIGITAL_ACCOUNT_OPENING',
    JOURNEY_END: 'JOURNEY_END'
}

export const EN_STATUS = {
    SUCCESS: true,
    COMPLETED_SUCCESS: 'COMPLETED_SUCCESS',
    COMPLETED_REJECTED: 'COMPLETED_REJECTED',
    FAILURE_TRANSIENT: 'FAILURE_TRANSIENT',
    FAILURE_NON_TRANSIENT: 'FAILURE_NON_TRANSIENT',
    ACCOUNT_ALLOCATION_COMPLETED: 'ACCOUNT_ALLOCATION_COMPLETED',
    ACCOUNT_ALLOCATION_FAILED: 'ACCOUNT_ALLOCATION_FAILED',
    ACCOUNT_ACTIVATION_IN_PROGRESS: 'ACCOUNT_ACTIVATION_IN_PROGRESS',
    ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',
    ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
    ACCOUNT_ACTIVATION_FAILED: 'ACCOUNT_ACTIVATION_FAILED',
    FUND_TRANSFER_COMPLETED: 'FUND_TRANSFER_COMPLETED',
    FUND_TRANSFER_TXN_DATE_EXCEEDED: 'FUND_TRANSFER_TXN_DATE_EXCEEDED',
    FUND_TRANSFER_FAILED: 'FUND_TRANSFER_FAILED'
}

export const PAYLOAD_LOG_POINT = {
    ESB_ACCOUNT_ALLOCATE_MS_REQUEST_ENCRYPTED: 'ESB_ACCOUNT_ALLOCATE_MS_REQUEST_ENCRYPTED',
    ESB_ACCOUNT_ALLOCATE_MS_REQUEST_DECRYPTED: 'ESB_ACCOUNT_ALLOCATE_MS_REQUEST_DECRYPTED',
    ESB_ACCOUNT_ALLOCATE_MS_RESPONSE: 'ESB_ACCOUNT_ALLOCATE_MS_RESPONSE',

    ESB_ACCOUNT_ALLOCATE_FAILURE: 'ESB_ACCOUNT_ALLOCATE_FAILURE',

    ESB_EFORM_ENQUIRE_MS_REQUEST: 'ESB_EFORM_ENQUIRE_MS_REQUEST',
    ESB_EFORM_ENQUIRE_MS_RESPONSE: 'ESB_EFORM_ENQUIRE_MS_RESPONSE',
    ESB_EFORM_ENQUIRE_FAILURE: 'ESB_EFORM_ENQUIRE_FAILURE',

    ESB_FUND_TRANSFER_MS_REQUEST: 'ESB_FUND_TRANSFER_MS_REQUEST',
    ESB_FUND_TRANSFER_MS_RESPONSE: 'ESB_FUND_TRANSFER_MS_RESPONSE',
    ESB_FUND_TRANSFER_FAILURE: 'ESB_FUND_TRANSFER_FAILURE',

    ESB_DIGITAL_ACCOUNT_OPENING_MS_REQUEST: 'ESB_DIGITAL_ACCOUNT_OPENING_MS_REQUEST',
    ESB_DIGITAL_ACCOUNT_OPENING_MS_RESPONSE: 'ESB_DIGITAL_ACCOUNT_OPENING_MS_RESPONSE',
    ESB_DIGITAL_ACCOUNT_OPENING_MS_FAILURE: 'ESB_DIGITAL_ACCOUNT_OPENING_MS_FAILURE',

    PRODUCT_ALLOCATION_MS_REQUEST: 'PRODUCT_ALLOCATION_MS_REQUEST',
    PRODUCT_ALLOCATION_MS_RESPONSE: 'PRODUCT_ALLOCATION_MS_RESPONSE',

    EFORMS_MS_REQUEST: 'EFORMS_MS_REQUEST',
    EFORMS_MS_RESPONSE: 'EFORMS_MS_RESPONSE',
    EFORMS_MS_FAILURE: 'EFORMS_MS_FAILURE',

    AADHAAR_GET_TOKEN_REQUEST: 'AADHAAR_GET_TOKEN_REQUEST',
    AADHAAR_GET_TOKEN_RESPONSE: 'AADHAAR_GET_TOKEN_RESPONSE',
    AADHAAR_GET_TOKEN_FAILURE: 'AADHAAR_GET_TOKEN_FAILURE',

    AADHAAR_LINKING_REQUEST: 'AADHAAR_LINKING_REQUEST',
    AADHAAR_LINKING_RESPONSE: 'AADHAAR_LINKING_RESPONSE',
    AADHAAR_LINKING_FAILURE: 'AADHAAR_LINKING_FAILURE',

    AADHAAR_SEEDING_REQUEST: 'AADHAAR_SEEDING_REQUEST',
    AADHAAR_SEEDING_RESPONSE: 'AADHAAR_SEEDING_RESPONSE',
    AADHAAR_SEEDING_FAILURE: 'AADHAAR_SEEDING_FAILURE',

    ORCH_CALLBACK_REQUEST: 'ORCH_CALLBACK_REQUEST',
    ORCH_CALLBACK_RESPONSE: 'ORCH_CALLBACK_RESPONSE'
}