export const QUERY_PARAM = {
    File_Name: 'file_name',
    Status: 'status',
    Total_Records: 'total_records',
    Created_At: 'createdAt',
    Count: 'COUNT',
    Sftp_File_Name: 'sftp_file_name',
    Disbursement_Data: 'disbursement_data',
    BATCH_ID: 'batch_id',
    SOURCE_SYSTEM: 'source_sytem',
    SPONSOR_BANK: 'sponsor_bank',
    SPONSOR_BANK_ACCOUNT_NUMBER: 'sponsor_bank_account_number',
    COMPANY_CODE: 'company_code',
    PRODUCT_CODE: 'product_code',
    SUB_PRODUCT_TYPE: 'sub_product_type',
    LOAN_NUMBER: 'loan_number',
    WEB_TOP: 'web_top',
    MICR_CODE: 'micr_code',
    IFSC_CODE: 'ifsc_code',
    BANK_NAME: 'bank_name',
    BRANCH_CODE: 'branch_code',
    CITY: 'city',
    CUSTOMER_NAME: 'customer_name',
    MOBILE_NUMBER: 'mobile_number',
    PERSONAL_EMAIL: 'personal_email',
    OFFICE_EMAIL: 'office_email',
    ACCOUNT_HOLDER_NAME: 'account_holder_name',
    ACCOUNT_NUMBER_AS_PER_MANDATE: 'account_number_as_per_mandate',
    ACCOUNT_TYPE: 'account_type',
    AMOUNT: 'amount',
    PAY_TO: 'pay_to',
    RUN_DATE: 'run_date',
    DOWNLOAD_BATCH_ID: 'download_batch_id',
    SOURCE_APPLICATIION_REFERENCE: 'source_application_reference',
    PAY_DATE: 'pay_date',
    CHQ_DATE: 'chq_date',
    TXN_ID: 'txn_id',
    IBL_REF_NUMBER: 'ibl_ref_number',
    STATUS: 'status',
    TXN_STATUS_DESC: 'txn_status_desc',
    TXN_STATUS_DESC_TC: 'txn_status_desc_tc',
    TXN_UTR: 'txn_utr',
    TXN_AMOUNT: 'txn_amount',
    TXN_TRANSACTION_TYPE: 'txn_transaction_type',
    TXN_PAYMENT_DATE: 'txn_payment_date',
    TXN_IMPS_BENE_NAME: 'txn_imps_bene_name',
    TXN_NXT_EXECUTION_DATE: 'txn_nxt_execution_date',
    ERROR_SUCCESS_MSG: 'error_success_msg',
    ERROR_STATUS: 'error_status',
    CUSTOMER_REF_NUMBER: 'customer_ref_number',
    USER_CODE: 'user_code',
    DISBURSEMENT_STATUS: 'disbursment_status',
    SOURCE_ID: 'source_id',
    SFDC_APP_ID: 'sfdc_app_id',
    OPPORTUNITY_ID: 'opportunity_id',
    LEAD_ID: 'lead_id',
    LOAN_AMOUNT: 'loan_amount',
    UNIQUE_COMBO_FIELD: 'unique_combo_field',
    BATCHNXT: 'batchnxt',
    GROUPID: 'groupid',
    LAST_UPDATED: 'Last_updated',
    ENACH: 'ENACH',
    ID: 'id',
    USER_ID: 'user_id',
    JSON_BODY: 'json_body',
    DESCRIPTION: 'description',
    UPDATEDAT: 'updatedAt',
    SOURCE_SYSTEM_UNIQUE_NUMBER: 'source_system_unique_number',
    MANDATE_REQUEST_ID: 'mandate_request_id',
    LOS_ID: 'los_id',
    PRODUCT_TYPE: 'product_type',
    ACCOUNT_NUMBER: 'account_number',
    CONTRIBUTION: 'contribution',
    MANDATE_STATUS: 'mandate_status',
    RESPONSE_REJECTION_REASON: 'response_rejection_reason',
    RESGISTRATION_DATE: 'registration_date',
    MANDATE_START_DATE: 'mandate_start_date',
    UMRN_NO: 'umrn_no',
    CONTRACT_NO: 'contract_no',
    DESC: 'DESC',
    SOURCE_SYSTEM1: 'source_system',
    LOAN_NO: 'loan_no',
    NULL: 'null',
    SYSTEM_CODE: 'system_code',
    REMARK: 'remark',
    MANDATE_MAXIMUM_AMOUNT: 'mandate_maximum_amount',
    FREQUENCY_CODE: 'frequency_code',
    REJECTION_CODE: 'rejection_code',
    VENDOR_TYPE: 'vendor_type',
    NOT_BANKED: 'Not banked',
    F1_PROVISION_STATUS: 'f1_provision_status',
    SINGLE: 'single',
    BULK: 'bulk',
    ADMIN: 'Admin',
    BNKDISBADMIN: 'BNKDISBADMIN',
    EMANDATE_AND_REVERSAL: 'EMANDATE_AND_REVERSAL',
    SYSTEMX_BULK: 'SYSTEMX_BULK',
    SWAP_PROVISION: 'SWAP_PROVISION',
    NOT_BANKED_PROVISIONAL_UPLOAD: 'NOT_BANKED_PROVISIONAL_UPLOAD',
    JOCATA_R: 'JOCATA_R',
    N: 'N',
    M: 'M',
    M_N_CASES_PROVISION: 'M_N_CASES_PROVISION',
    OPEN_MANDATE: 'OPEN_MANDATE',
    F1_HEALTH_REJECT: 'F1_HEALTH_REJECT',
    EMANDATE_EXCEPTION: 'EMANDATE_EXCEPTION',
    OPEN_MANDATE_REGULAR_REPORTS: 'OPEN_MANDATE_REGULAR_REPORTS',
    FILE_EXTENSION: 'file_extension',
    BANK_CODE: 'bank_code',
    FOLDER: 'folder',
    S3_KEY: 's3_key',
    DE_MERGE_FLAG: 'de_merge_flag',
    MAX: 'max',
    TOTAL: 'total',
    UI_API_LOG_CREATEDAT: 'ui_api_logs.createdAt',
    F1_REVERSAL_SFTP_PUSH: 'F1_REVERSAL_SFTP_PUSH',
    REGISTRATION: 'Registration',
    REVERSAL: 'Reversal',
    REPRESENTATION_BOUNCE_CASES: 'representation_bounce_cases',
    REPRESENTATION_POST_REPORTS: 'representation_post_reports',
    ALL: 'All',
    REG_PRE_REPORTS: 'reg_pre_reports',
    REG_POST_REPORTS: 'reg_post_reports',
    MANDATE_TYPE: 'mandate_type',
    DOCUMENT_TYPE: 'document_type',
    MANDATE_END_DATE: 'mandate_end_date',
    CYCLE_DATE: 'cycle_date',
    CATEGORY_CODE: 'category_code',
    RESPONSE_STATUS: 'response_status',
    RESPONSE_REMARKS: 'response_remarks',
    MERGE_BATCH_ID: 'merge_batch_id',
    MERGE_DATE_TIME: 'merge_date_time',
    REVERSAL_BATCH_ID: 'reversal_batch_id',
    REVERASL_BATCH_ID: 'reverasl_batch_id',
    DEMERGE_FILENAME: 'demerge_filename',
    DEMERGE_DATE_TIME: 'demerge_date_time',
    CONTRIBUTION_BASIS: 'contribution_basis',
    TRAN_PRE_REPORTS: 'tran_pre_reports',
    TRAN_POST_REPORTS: 'tran_post_reports',
    MANDATE_AMOUNT: 'mandate_amount',
    PRESENTATION_REMARK: 'presentation_Remark',
    SOURCE_SYSTEM_UNIQUE_NUMBER1: 'source_System_uniq_number',
    MERGE_USER_NAME: 'merge_user_name',
    DEMERGE_FILE_NAME: 'demerge_file_name',
    DEMERGE_USER_NAME: 'demerge_user_name',
    REPRESENTATION_PRE_REPORTS: 'representation_pre_reports',
    REPRESENTATION_BOUNCE_REPORT1: 'Representation Bounce Report',
    DT_REPRESENTATION_RESPONSE_REPORT1: 'DT Re-presentation Response from Bank Report',
    REG_SENT_BANK_REPORT: 'Reg Sent To Bank Report',
    REG_BANK_RESPONSE_REPORT: 'Reg Bank Response Report',
    DT_SENT_BANK_REPORTS: 'DT Sent To Bank Reports',
    DT_BANK_RESPONSE_REPORTS: 'DT Bank Response Report',
    DT_REPRESENTATION_BANK_REPORTS: 'DT Re-presentation Sent To Bank Report',
    MANDATE_START: 'mandate_start',
    SETTALEMENT_DATE: 'settalement_date',
    UTILITY_CODE: 'utility_code',
    PRESENTATION_MODE: 'presentment_mode',
    UPLOAD_STATUS: 'upload_status',
    UPLOAD_REJECT_REASON: 'upload_reject_reason',
    REPRESENTATION: 'Representation',
    MANDATE_DATE: 'Mandate_date',
    SETTLEMENT_DATE1: 'Settlement_date',
    UMRN1: 'UMRN',
    AMOUNT_IN_RUPEES: 'Amount_in_rupees',
    LOAN_ACCOUNT_NO: 'Loan_Account_no',
    RPT_PROVISION_UPLOAD: 'RPT Provision Upload',
    BATCH_IS_APPROVED: 'Batch is Approved!!',
    BATCH_IS_REJECTED: 'Batch is Rejected!!',
    BATCH_IS_ALREADY_REJECTED: ' Batch is Already Rejected, Cant Approve',
    BATCH_IS_ALREADY_APPROVED: 'Batch is Already Approved, Cant Reject',
    SUCCESS: 'Success',
    PENDING: 'Pending',
    FINNONE: 'FINNONE',
    BANCS: 'BANCS',
    NACH: 'NACH',
    AD: 'AD',
    LEG: 'LEG',
    HDFC: 'HDFC',
    HDFC_NUPAY :'HDFC NUPAY',
    SAPECC6: 'SAPECC6',
    PRESENTATION: 'Presentation',
    ConsolidateBank: 'Consolidate Bank',
    SAP: 'SAP',
    PDC: 'PDC',
    TPSL: 'TPSL',
    SBI: 'SBI',
    txt: 'txt',
    TXT: 'TXT',
    csv: 'csv',
    CSV: 'CSV',
    xls: 'xls',
    UPI : 'UPI Mandate',
    PROCESSING: 'Processing',
    MANUAL: 'MANUAL',
    TCFSL:'7000',
    TCHFL:'9000',
    ECS:'ECS',
    TCL_AC_NO_5_FIELD:'00600310031247',
    TCHFL_AC_NO_5_FIELD:'57500000165558',
    CLEAR:'C',
    BOUNCED:'B',
    CLEAR_CODE:'00',
    ICICI_BANK:'229',
    FIVE_FIELD:'fivefield',
    BANKING_FILE:'BANK',
    PROCESSING_FILE_LAMBDA:'processing-file',
    BANKINGFILE:'BANKINGFILE',
    FIVEFIELD:'FIVEFIELD',
    MERGE_REPORT_UAT:'Merge-Reprt-UAT',
    EVENT:'Event',
    TW:'TW',
    ICICI :'ICICI',
    AXIS : 'AXIS',
    ICICITPSL:'ICICI TPSL'
  }
  
  export const DATE_FORMAT = {
    DD_MM_YYYY: 'DD-MM-YYYY',
    YYYY_MM_DD: 'YYYY-MM-DD',
    YYYY_MM_DD_HH_mm_ss: 'YYYY-MM-DD HH:mm:ss',
    YYYY_MM_DD_HH_mm_ss_A: 'YYYY-MM-DD HH:mm:ss A',
    DDMMYYYY: 'DDMMYYYY',
    YYYYMMDDHHmmss: 'YYYYMMDDHHmmss',
    DDMMYYYYHHMMA:'DD/MM/YYYY hh:mm A',
    DDMMYYYYNOHHMMA:'DD/MM/YYYY',
    DDMMYYYYDOT:'DD.MM.YYYY'
  }
  
  export const TIME_FORMAT = {
    START_TIME: ' 00:00:00',
    END_TIME: ' 23:59:59'
  }
  
  export const FILE_FORMAT = {
    SPLIT: '/',
    BINARY: 'binary',
    csv: '.csv',
    ROW_DELIMITER: '\t',
    XLS: 'xls',
    BAR: '|',
    txt: '.txt',
    TXT: 'TXT',
    COMMA: ','
  }
  
  export const SUB_MODULE_NAME={
    NOTIFY_USER_API:'notifyUser',
  }
  export const MODULE_NAME = {
    DT: 'DEBIT TRANSACTION',
    DEMERGE: 'DEMERGE',
    MERGE: 'MERGE',
    FILE_UPLOAD: 'FILE_UPLOAD',
    RPT: 'Representation',
    UPI_ICICI:'UpiICICI'
  }
  
  export const FUNCTION_NAME = {
    DEMERGE_REJECT_DOWNLOAD: 'Demerge Reject Download',
    DEMERGE_SOURCE_SYSTEM_COUNT: 'Demerge Source System Count',
    DEMERGE_SUCCESS_DOWNLOAD: 'Demerge Success File',
    DEMERGE_FETCH_MANUAL_COUNT: 'Demerge Fetch Manual Count',
    DEMERGE_MANUAL_DOWNLOAD: 'Demerge  Manual Source Download',
    MERGE_FIVE_FIELD: 'merge Five Field Download',
    MERGE_BANKING_FILE: 'merge Banking File Download',
    MERGE_DATA: 'merge Data',
    PRESENTATION_FILE_UPLOAD: 'PRESENTATION File Upload',
    DEMERGE_FILE_UPLOAD: 'Demerge File Upload',
    PRESENTATION_REJECT_FILE: 'Presentation Reject File',
    APPROVE_FLAG: 'Approve Flag Button',
    REJECT_FLAG: 'Reject Flag Button',
    DOWNLOAD_RPT_SUCCESS: 'Download Rpt Success File',
    DOWNLOAD_RPT_REJECT: 'Download Rpt Reject File',
    RPT_FILE_UPLOAD: 'RPT File Upload',
    BILL_UPLOAD: 'Bill Upload',
    OTU: 'RPT OTU',
    NOTIFY_USER:'NotifyUsersAPI',
    EXECUTE_UPI_TRANSECTION:'executeApiTransection',
    UPI_TRANSECTION_STATUS:'upiTransectionStatus',
    PROCESS_CSV_FROM_S3:"processCsvFromS3"
  }
  
  export const LOGGER_CODES = {
    INFO: 'Info',
    ERROR: 'error',
    SUCCESS: 'success'
  }
  
  export const S3_FILE_PATH = {
    DT: 'DebitTransaction',
    PRESENTATION: 'Presentation',
    MERGE: 'Merge',
    DEMERGE: 'Demerge',
    RPT_BILL_UPLOAD: 'RptBillUpload',
    RPT_PROVISION_UPLOAD: 'RptProvisionUpload',
    DOWNLOADS: 'Downloads',
    REJECT: 'Reject',
    SUCCESS: 'Success',
    UPLOADS: 'Uploads',
    FIVE_FIELD: 'FiveField',
    BANKING_FILE: 'BankFile'
  }
  
  export const FILE_LOCATION = {
    DOWNLOAD: 'download/',
    DEMERGE_FILE: 'download/download.csv',
    DEMERGE_MUL_FILE: 'download/downloadMultiple.csv',
    DISBURSEMENT_REPORT: 'download/SFTP_FILE_LIST.xlsx',
    DISBURSEMENT_TABLE_REPORT: 'download/disbursement_data.xlsx',
    EMANDATE_REPORT: 'download/emandate_log.xlsx',
    ENACH_ADOPTION: 'download/Enach_Daily_Rpt_',
    SWAP_ENACH: 'download/SWAP_ENACH_REPORT_',
    ENACH_NOT_BANK: 'download/enach_not_banked_data.xlsx',
    OPEN_MANDATE: 'OpenMandate_',
    PAYMENT_REPORT: 'download/bulk_reports.xlsx',
    FIVE_FIELD: 'download/bulk.xlsx',
    F1_STATUS: 'download/F1 Status File.xls',
    SMS_REPORT: 'download/registration status SMS report.xlsx',
    DT_REPORT: 'download/pre_post_reports/',
    De_MERGE: 'download/statusDownload.xlsx',
    Merge_download: 'download/MergeDownload.xlsx',
    S3_KEY: 'commonUpload/dtDemergeUpload',
    Download_Txt: 'download/download.txt',
    S3_KEY_Lambda: 'commonUpload/integrationUpload/rawFile',
    Download_Five_Field: '`commonUpload/dtMergeFile/bulk.xlsx',
    Download_Merge_data: 'commonUpload/dtMerge/'
  }
  
  export const FIVE_FIELD_FILE_NAME = {
    TCFSL: {
      NACH_TCFSL_HDFC00065000003219: "NACH_TCFSL_HDFC00065000003219_",
      NACH_TCFSL_HDFC00065000003219_Nupay: "NACH_TCFSL_HDFC00065000003219_Nupay_"
    },
    TCHFL: {
      NACH_TCHFL_HDFC00064000003218: "NACH_TCHFL_HDFC00064000003218_",
      NACH_TCHFL_HDFC00064000003218_Nupay: "NACH_TCHFL_HDFC00064000003218_Nupay_"
    }
  }

  export const ICICI_RESPONSE_STATUS={
    'APPROVED OR COMPLETED SUCCESSFULLY': 67,
    'DEBIT HAS BEEN FAILED|Z9|INSUFFICIENT FUNDS IN CUSTOMER (REMITTER) ACCOUNT':44
  }

  export const UPI_CONSTANT = {
    UPI : "UPI Mandate",
    UPI_SORUCE_SYSTEM : "FINNONE",
    EXE_SUCCESS_CODE : '92',
    PDN_SUCCESS_CODE : '0'
  }
  
  export const TABLE_NAMES = {
    DEBIT_TRAN_REG : "debit_tran_reg",
    DEBIT_TRAN_RES : "debit_tran_res",
    MANUAL_MANDATE : "manualMandate",
    DEBIT_TRAN_REVERSAL_RES:"debitTransactionReversalResponse",
    DEBIT_TRAN_FILE_UPLOAD_STATUS : "debit_tran_reg_file_upload_status",
    ADVANCE_EMI: "advance_emi",
    API_REQ_RES_LOGS: "api_req_res_logs",
    USER: "user"
  }